vich_uploader:
    db_driver: orm
    mappings:
        multimedia:
            uri_prefix:        '%app.path.multimedia%'
            upload_destination: '%kernel.project_dir%/public/multimedia'
            namer: Vich\UploaderBundle\Naming\UniqidNamer


            inject_on_load:     true
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
