vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix:         '% app.path.multimedia%'
            upload_destination: '%kernel.project_dir%/public%app.path.multimedia%'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
